name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  release_branch_type:
    description: 'Release branch type name'
    required: false
    default: 'release'
  develop_branch:
    description: 'Develop branch name'
    required: false
    default: 'develop'
runs:
  using: 'node16'
  main: 'dist/index.js'
